// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQCITPv_szN6NKGQn05X3cZQQ-9xwC7LU',
    appId: '1:74185747401:web:477bd2ad7dba940a719618',
    messagingSenderId: '74185747401',
    projectId: 'mynotes-flutter-begineer',
    authDomain: 'mynotes-flutter-begineer.firebaseapp.com',
    storageBucket: 'mynotes-flutter-begineer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU1GeB-TdX9VQUSqxkKZnafZb_yf08HtY',
    appId: '1:74185747401:android:ac842f82c2205b3a719618',
    messagingSenderId: '74185747401',
    projectId: 'mynotes-flutter-begineer',
    storageBucket: 'mynotes-flutter-begineer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsicU56P1WBp0LPFTTRbuSs0GS4snwz98',
    appId: '1:74185747401:ios:33cc2444abfb4aee719618',
    messagingSenderId: '74185747401',
    projectId: 'mynotes-flutter-begineer',
    storageBucket: 'mynotes-flutter-begineer.appspot.com',
    iosClientId: '74185747401-tsd6c5t4mo8oqgpdj58g3pm2sgbt2dab.apps.googleusercontent.com',
    iosBundleId: 'flutter1.flutterBegineer',
  );
}
